apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp7s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.101.0/24",
        "rangeStart": "192.168.101.100",
        "rangeEnd": "192.168.101.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.101.1"
      }
    }'